#pragma once

#ifndef	SPCR_VERSION_INCLUDED
#define SPCR_VERSION_INCLUDED

#define MAKE_STR_HELPER(x) #x
#define MAKE_STR(x) MAKE_STR_HELPER(x)

#define SPCR_VERSION_MAJOR		1
#define SPCR_VERSION_MINOR		0
#define SPCR_VERSION_PATCH		0
#define SPCR_VERSION_BETA		0
#define SPCR_VERSION_VERSTRING	MAKE_STR(SPCR_VERSION_MAJOR) "." MAKE_STR(SPCR_VERSION_MINOR) "." MAKE_STR(SPCR_VERSION_PATCH) "." MAKE_STR(SPCR_VERSION_BETA)

#endif
